import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { textResult } from "../../shared/mcp-utils.js";
import { createNexusPaths, ensureDir, ensureFile, findProjectRoot } from "../../shared/paths.js";

const execFileAsync = promisify(execFile);

async function scanProject(root: string) {
  const topLevel = (await readdir(root, { withFileTypes: true }))
    .filter((entry) => ![".git", ".nexus", ".codex", "node_modules", "dist"].includes(entry.name))
    .map((entry) => (entry.isDirectory() ? `${entry.name}/` : entry.name))
    .sort();

  let scripts: string[] = [];
  if (existsSync(path.join(root, "package.json"))) {
    try {
      const pkg = JSON.parse(await readFile(path.join(root, "package.json"), "utf8")) as {
        scripts?: Record<string, string>;
      };
      scripts = Object.keys(pkg.scripts ?? {}).sort();
    } catch {
      scripts = [];
    }
  }

  const docs = ["AGENTS.md", "README.md", "CLAUDE.md"].filter((name) => existsSync(path.join(root, name)));
  const recentCommits = await (async () => {
    try {
      const { stdout } = await execFileAsync("git", ["log", "-5", "--pretty=format:%s"], { cwd: root });
      return stdout.split("\n").map((line) => line.trim()).filter(Boolean);
    } catch {
      return [] as string[];
    }
  })();

  return { topLevel, scripts, docs, recentCommits };
}

function draftDoc(title: string, tags: string, bodyLines: string[]): string {
  return [`<!-- tags: ${tags} -->`, `# ${title}`, "", ...bodyLines, ""].join("\n");
}

export function registerWorkflowTools(server: McpServer): void {
  server.tool(
    "nx_init",
    "Initialize .nexus core knowledge from the repository",
    {
      mission: z.string().optional(),
      design: z.string().optional(),
      roadmap: z.string().optional(),
      setup_rules: z.boolean().optional()
    },
    async ({ mission, design, roadmap, setup_rules }) => {
      const projectRoot = findProjectRoot();
      const paths = createNexusPaths(projectRoot);
      await Promise.all([
        ensureDir(paths.NEXUS_ROOT),
        ensureDir(paths.CONTEXT_ROOT),
        ensureDir(paths.MEMORY_ROOT),
        ensureDir(paths.RULES_ROOT),
        ensureDir(paths.STATE_ROOT),
        ensureDir(paths.HARNESS_STATE_ROOT)
      ]);
      await ensureFile(paths.HISTORY_FILE, JSON.stringify({ cycles: [] }, null, 2) + "\n");

      const scan = await scanProject(projectRoot);
      const generated: string[] = [];

      const architecturePath = path.join(paths.CONTEXT_ROOT, "architecture.md");
      await writeFile(
        architecturePath,
        draftDoc("Architecture", "codebase, architecture", [
          "## Top-level Structure",
          ...scan.topLevel.map((entry) => `- ${entry}`),
          "",
          "## Notes",
          "- Generated by nx_init from current repository structure.",
          "- Replace draft language with confirmed architecture boundaries."
        ]),
        "utf8"
      );
      generated.push("context/architecture.md");

      const developmentPath = path.join(paths.CONTEXT_ROOT, "development.md");
      await writeFile(
        developmentPath,
        draftDoc("Development Workflow", "codebase, development", [
          `- Scripts: ${scan.scripts.join(", ") || "none detected"}`,
          `- Docs: ${scan.docs.join(", ") || "none detected"}`,
          "",
          "## Recent Activity",
          ...scan.recentCommits.map((commit) => `- ${commit}`)
        ]),
        "utf8"
      );
      generated.push("context/development.md");

      const missionPath = path.join(paths.CONTEXT_ROOT, "mission.md");
      await writeFile(
        missionPath,
        draftDoc("Mission", "identity, mission", [
          mission?.trim() || "Draft mission generated by nx_init. Replace with the confirmed product goal and user value."
        ]),
        "utf8"
      );
      generated.push("context/mission.md");

      const designPath = path.join(paths.CONTEXT_ROOT, "design.md");
      await writeFile(
        designPath,
        draftDoc("Design", "identity, design", [
          design?.trim() || "Draft design rationale generated by nx_init. Replace with confirmed architecture decisions and trade-offs."
        ]),
        "utf8"
      );
      generated.push("context/design.md");

      const roadmapPath = path.join(paths.CONTEXT_ROOT, "roadmap.md");
      await writeFile(
        roadmapPath,
        draftDoc("Roadmap", "identity, roadmap", [
          roadmap?.trim() || "Draft roadmap generated by nx_init. Replace with the next 1-3 confirmed priorities."
        ]),
        "utf8"
      );
      generated.push("context/roadmap.md");

      if (setup_rules) {
        const rulesPath = path.join(paths.RULES_ROOT, "dev-rules.md");
        await writeFile(
          rulesPath,
          draftDoc("Dev Rules", "dev, workflow", [
            "- Use [plan] before major implementation decisions.",
            "- Register tasks before non-trivial execution.",
            "- Run nx_sync after meaningful completed cycles."
          ]),
          "utf8"
        );
        generated.push("rules/dev-rules.md");
      }

      return textResult({
        initialized: true,
        generated_files: generated,
        next_steps: [
          "Confirm mission/design/roadmap drafts.",
          "Use [plan] before major implementation work.",
          "Use nx_sync after completed cycles to refresh core knowledge."
        ]
      });
    }
  );

  server.tool(
    "nx_sync",
    "Sync .nexus/context guidance with current repository state",
    {},
    async () => {
      const projectRoot = findProjectRoot();
      const paths = createNexusPaths(projectRoot);
      await ensureDir(paths.CONTEXT_ROOT);
      const scan = await scanProject(projectRoot);

      const syncPath = path.join(paths.CONTEXT_ROOT, "development.md");
      await writeFile(
        syncPath,
        draftDoc("Development Workflow", "codebase, development", [
          `- Scripts: ${scan.scripts.join(", ") || "none detected"}`,
          `- Docs: ${scan.docs.join(", ") || "none detected"}`,
          "",
          "## Recent Activity",
          ...scan.recentCommits.map((commit) => `- ${commit}`),
          "",
          "> Refreshed by nx_sync."
        ]),
        "utf8"
      );

      return textResult({
        synced: true,
        updated: ["context/development.md"],
        guidance: "Review architecture, mission, design, and roadmap docs for stale statements that still need human confirmation."
      });
    }
  );
}
